[versions]

# Toolchain
java = "21"
java-target = "17"
kotlin = "2.3.21"

# Build / publishing plugins
plugin-publish = "2.1.1"
vanniktech-maven-publish = "0.37.0"

# Loader tooling
loom = "1.17.13"
moddevgradle = "2.0.141"
access-widener = "2.1.0"
accesstransformers = "13.0.3"

# JUnit
junit = "6.1.1"

# Coverage
jacoco = "0.8.15"

# Miscellaneous
kotlin-semver = "3.1.0"


[libraries]

# Plugins
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-publish-plugin = { module = "com.gradle.publish:plugin-publish-plugin", version.ref = "plugin-publish" }
vanniktech-maven-publish-plugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "vanniktech-maven-publish" }

# Loader tooling
fabric-loom = { module = "net.fabricmc:fabric-loom", version.ref = "loom" }
moddev-gradle = { module = "net.neoforged:moddev-gradle", version.ref = "moddevgradle" }
access-widener = { module = "net.fabricmc:access-widener", version.ref = "access-widener" }
accesstransformers = { module = "net.neoforged:accesstransformers", version.ref = "accesstransformers" }

# JUnit
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

# Miscellaneous
kotlin-semver = { module = "io.github.z4kn4fein:semver", version.ref = "kotlin-semver" }


[plugins]

kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "plugin-publish" }
