[versions]

# Toolchain
java = "21"
javaTarget = "17"
kotlin = "2.3.21"

# Build / publishing plugins
pluginPublishPlugin = "2.1.1"
gradleMavenPublishPlugin = "0.37.0"

# JUnit
junit = "6.1.1"

# Coverage
jacoco = "0.8.15"

# Miscellaneous
nightconfig = "3.8.3"

################################################################################
################################################################################

[libraries]

# Plugins
plugin-kotlinGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-publishPlugin = { module = "com.gradle.publish:plugin-publish-plugin", version.ref = "pluginPublishPlugin" }
plugin-vanniktechMavenPublish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "gradleMavenPublishPlugin" }

# Loader tooling
fabricLoom = { module = "net.fabricmc:fabric-loom", version = "1.17.13" }
moddevGradle = { module = "net.neoforged:moddev-gradle", version = "2.0.141" }
accessWidener = { module = "net.fabricmc:access-widener", version = "2.1.0" }
accesstransformers = { module = "net.neoforged:accesstransformers", version = "13.0.3" }

# NightConfig
nightconfig-json = { module = "com.electronwill.night-config:json", version.ref = "nightconfig" }
nightconfig-toml = { module = "com.electronwill.night-config:toml", version.ref = "nightconfig" }

# JUnit
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platformLauncher = { module = "org.junit.platform:junit-platform-launcher" }

# Miscellaneous
kotlinSemver = { module = "io.github.z4kn4fein:semver", version = "3.1.0" }

################################################################################
################################################################################

[bundles]

nightconfig-all = ["nightconfig-json", "nightconfig-toml"]

################################################################################
################################################################################

[plugins]

kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "pluginPublishPlugin" }
