package com.oliveryasuna.modkit.scaffold.render

import com.oliveryasuna.modkit.core.extension.McLoader
import com.oliveryasuna.modkit.scaffold.ScaffoldModule
import com.oliveryasuna.modkit.scaffold.ScaffoldPlan
import com.oliveryasuna.modkit.scaffold.ScaffoldShape

/**
 * Renders the example sources: a loader-appropriate mod entry point per
 * selected loader — Fabric's a `ModInitializer` (wired into `fabric.mod.json`
 * `entrypoints.main`), NeoForge's a `@Mod` class — and, when `mixins` is
 * selected, an example mixin config plus a placeholder mixin package.
 *
 * In the single-loader simple shape one plain entry class is emitted. In the
 * multiversion shape both loaders' bootstraps share one source set, so each is
 * wrapped in a Stonecutter `//? if <loader>` guard (the active node's loader
 * uncommented, the others commented) — the same pattern as the `example-mod`.
 * Pure string builders.
 */
internal object SourceRenderer {

    fun render(plan: ScaffoldPlan): List<GeneratedFile> {
        val files = mutableListOf<GeneratedFile>()

        val multiversion = plan.shape == ScaffoldShape.MULTIVERSION
        val activeLoader = plan.nodes.first().loader

        plan.nodes.map { it.loader }.distinct().forEach { loader ->
            val pkg = Naming.entryPackage(plan, loader)
            val name = Naming.entryClassName(plan, loader)
            val body = when(loader) {
                McLoader.FABRIC -> fabricEntry(plan, pkg, name)
                else -> neoForgeEntry(plan, pkg, name)
            }
            val content = if(multiversion) guard(loader, active = loader == activeLoader, body) else body

            files += GeneratedFile("src/main/java/${pkg.replace('.', '/')}/$name.java", content)
        }

        if(plan.modules.contains(ScaffoldModule.MIXINS)) {
            files += renderMixin(plan)
        }

        return files
    }

    private fun fabricEntry(plan: ScaffoldPlan, pkg: String, name: String): String = buildString {
        appendLine("package $pkg;")
        appendLine()
        appendLine("import net.fabricmc.api.ModInitializer;")
        appendLine()
        // Line comments only — a block comment here would nest inside the
        // Stonecutter `/* */` guard used for the inactive loader
        // (multiversion).
        appendLine("// Fabric entry point for '${plan.modId}', generated by Modkit.")
        appendLine("// Referenced from fabric.mod.json entrypoints.main (wired by the metadata plugin).")
        appendLine("public final class $name implements ModInitializer {")
        appendLine()
        appendLine("    public static final String MOD_ID = \"${plan.modId}\";")
        appendLine()
        appendLine("    @Override")
        appendLine("    public void onInitialize() {")
        appendLine("        System.out.println(\"Hello from \" + MOD_ID + \"!\");")
        appendLine("    }")
        appendLine("}")
    }

    private fun neoForgeEntry(plan: ScaffoldPlan, pkg: String, name: String): String = buildString {
        appendLine("package $pkg;")
        appendLine()
        appendLine("import net.neoforged.bus.api.IEventBus;")
        appendLine("import net.neoforged.fml.common.Mod;")
        appendLine()
        // Line comments only — see the note in fabricEntry.
        appendLine("// NeoForge entry point for '${plan.modId}', generated by Modkit.")
        appendLine("// Discovered by the @Mod annotation — no manifest entry needed.")
        appendLine("@Mod(\"${plan.modId}\")")
        appendLine("public final class $name {")
        appendLine()
        appendLine("    public static final String MOD_ID = \"${plan.modId}\";")
        appendLine()
        appendLine("    public $name(final IEventBus modBus) {")
        appendLine("        System.out.println(\"Hello from \" + MOD_ID + \"!\");")
        appendLine("    }")
        appendLine("}")
    }

    /**
     * Wraps a Java file [body] in a Stonecutter loader guard. The active
     * loader's body is left as-is; an inactive loader's body is
     * block-commented, so only one loader's bootstrap compiles per node.
     */
    private fun guard(loader: McLoader, active: Boolean, body: String): String {
        val tag = Naming.loaderTag(loader)
        return if(active) {
            "//? if $tag {\n$body//?}\n"
        } else {
            "//? if $tag {\n/*$body*///?}\n"
        }
    }

    private fun renderMixin(plan: ScaffoldPlan): List<GeneratedFile> {
        val pkg = Naming.basePackage(plan)
        val pkgPath = Naming.basePackagePath(plan)
        val mixinPkg = "$pkg.mixin"
        val mixinPkgPath = "$pkgPath/mixin"
        return listOf(
            GeneratedFile(
                path = "src/main/resources/${plan.modId}.mixins.json",
                content = buildString {
                    appendLine("{")
                    appendLine("  \"required\": true,")
                    appendLine("  \"package\": \"$mixinPkg\",")
                    appendLine("  \"compatibilityLevel\": \"JAVA_17\",")
                    appendLine("  \"mixins\": [],")
                    appendLine("  \"client\": [],")
                    appendLine("  \"injectors\": {")
                    appendLine("    \"defaultRequire\": 1")
                    appendLine("  }")
                    appendLine("}")
                }
            ),
            GeneratedFile(
                path = "src/main/java/$mixinPkgPath/package-info.java",
                content = buildString {
                    appendLine("/**")
                    appendLine(" * Place your @Mixin classes for '${plan.modId}' in this package.")
                    appendLine(" */")
                    appendLine("package $mixinPkg;")
                }
            ),
        )
    }
}
