package com.oliveryasuna.modkit.scaffold.render

import com.oliveryasuna.modkit.scaffold.ScaffoldModule
import com.oliveryasuna.modkit.scaffold.ScaffoldPlan

/**
 * Renders the example sources shared by both project shapes: a trivial mod
 * entry class, and — when `mixins` is selected — an example mixin config plus a
 * placeholder mixin package. Pure string builders.
 */
internal object SourceRenderer {

    fun render(plan: ScaffoldPlan): List<GeneratedFile> {
        val files = mutableListOf<GeneratedFile>()
        val pkg = Naming.basePackage(plan)
        val pkgPath = Naming.basePackagePath(plan)
        val className = Naming.modClassName(plan)

        files += GeneratedFile(
            path = "src/main/java/$pkgPath/$className.java",
            content = buildString {
                appendLine("package $pkg;")
                appendLine()
                appendLine("/**")
                appendLine(" * Example entry point for the '${plan.modId}' mod, generated by Modkit.")
                appendLine(" */")
                appendLine("public final class $className {")
                appendLine()
                appendLine("    public static final String MOD_ID = \"${plan.modId}\";")
                appendLine()
                appendLine("    public $className() {")
                appendLine("        System.out.println(\"Hello from \" + MOD_ID + \"!\");")
                appendLine("    }")
                appendLine("}")
            }
        )

        if(plan.modules.contains(ScaffoldModule.MIXINS)) {
            files += renderMixin(plan, pkg, pkgPath, className)
        }

        return files
    }

    private fun renderMixin(
        plan: ScaffoldPlan,
        pkg: String,
        pkgPath: String,
        className: String,
    ): List<GeneratedFile> {
        val mixinPkg = "$pkg.mixin"
        val mixinPkgPath = "$pkgPath/mixin"
        return listOf(
            GeneratedFile(
                path = "src/main/resources/${plan.modId}.mixins.json",
                content = buildString {
                    appendLine("{")
                    appendLine("  \"required\": true,")
                    appendLine("  \"package\": \"$mixinPkg\",")
                    appendLine("  \"compatibilityLevel\": \"JAVA_17\",")
                    appendLine("  \"mixins\": [],")
                    appendLine("  \"client\": [],")
                    appendLine("  \"injectors\": {")
                    appendLine("    \"defaultRequire\": 1")
                    appendLine("  }")
                    appendLine("}")
                }
            ),
            GeneratedFile(
                path = "src/main/java/$mixinPkgPath/package-info.java",
                content = buildString {
                    appendLine("/**")
                    appendLine(" * Place your @Mixin classes for '${plan.modId}' in this package.")
                    appendLine(" */")
                    appendLine("package $mixinPkg;")
                }
            ),
        )
    }
}
