package com.oliveryasuna.modkit.loaders

import net.fabricmc.accesswidener.AccessWidenerReader
import net.fabricmc.accesswidener.AccessWidenerReader.AccessType
import net.fabricmc.accesswidener.AccessWidenerVisitor
import net.neoforged.accesstransformer.parser.AtParser
import java.io.StringReader

/**
 * Converts Fabric access wideners to a NeoForge access transformer.
 *
 * Parsing (the format-tracking, correctness-critical part) is delegated to
 * Fabric's `access-widener` library; this owns only the mapping from AW
 * semantics to AT lines, and validates the result through NeoForge's own AT
 * parser. The mapping is deliberately **widening-only**:
 *
 * - every widened target becomes `public` (AW
 * `accessible`/`extendable`/`mutable`); - `extendable` (subclass/override) and
 * `mutable` (writable field) additionally
 * strip `final` via the `-f` suffix.
 *
 * It never narrows access, so the mod always compiles and runs on NeoForge; the
 * extra visibility (e.g. an `extendable` protected member becoming public) is a
 * dev-time concern only. Names are converted from internal (`a/b/C`) to the
 * dotted form AT uses; method descriptors are preserved.
 */
internal object AwToAt {

    /**
     * Converts one or more access-widener file contents into a single AT file body.
     */
    fun convert(accessWideners: List<String>): String {
        val collector = Collector()
        accessWideners.forEach { content ->
            content.reader().buffered().use { AccessWidenerReader(collector).read(it) }
        }
        val accessTransformer = collector.render()

        // Round-trip through NeoForge's parser so a malformed mapping fails
        // here, not later inside MDG.
        StringReader(accessTransformer).use { AtParser.parse(it, "modkit-generated", { _, _ -> }) }

        return accessTransformer
    }

    private class Collector : AccessWidenerVisitor {

        // Ordered so output is deterministic: target line (sans access) ->
        // stripFinal.
        private val targets = linkedMapOf<String, Boolean>()

        private fun record(target: String, access: AccessType) {
            val stripFinal = access == AccessType.EXTENDABLE || access == AccessType.MUTABLE
            targets.merge(target, stripFinal) { existing, next -> existing || next }
        }

        override fun visitClass(name: String, access: AccessType, transitive: Boolean) {
            record(dotted(name), access)
        }

        override fun visitMethod(owner: String, name: String, descriptor: String, access: AccessType, transitive: Boolean) {
            record("${dotted(owner)} $name$descriptor", access)
        }

        override fun visitField(owner: String, name: String, descriptor: String, access: AccessType, transitive: Boolean) {
            record("${dotted(owner)} $name", access)
        }

        fun render(): String = buildString {
            append("# Generated by Modkit from access wideners. Do not edit.\n")
            targets.forEach { (target, stripFinal) ->
                append(if(stripFinal) "public-f " else "public ").append(target).append('\n')
            }
        }

        private fun dotted(internalName: String): String = internalName.replace('/', '.')

    }

}
