package com.oliveryasuna.modkit.ci

/**
 * Turns a resolved [CiWorkflowInputs] into a GitHub Actions workflow document.
 * The output is deterministic — the matrix is sorted and keys are emitted in a
 * fixed order — so a drift check can diff a regenerated document against the
 * committed one.
 */
internal object CiWorkflowBuilder {

    fun build(inputs: CiWorkflowInputs): String {
        val matrix = inputs.matrix.sortedWith(compareBy({ it.minecraftVersion }, { it.loader }))
        val javaVersion = "\"${inputs.java}\""
        val publishJob = inputs.publishOnTag && inputs.publishApplied

        return buildString {
            appendLine("# Generated by Modkit. Do not edit; run generateCiWorkflows.")
            appendLine("name: CI")
            appendLine("on:")
            appendLine("  push:")
            appendLine("    branches: [\"**\"]")
            appendLine("    tags: [\"v*\"]")
            appendLine("  pull_request:")
            appendLine("jobs:")
            appendLine("  build:")
            appendLine("    strategy:")
            appendLine("      fail-fast: false")
            appendLine("      matrix:")
            appendLine("        include:")
            for(entry in matrix) {
                appendLine("          - minecraft: \"${entry.minecraftVersion}\"")
                appendLine("            loader: \"${entry.loader}\"")
            }
            appendLine("    runs-on: ubuntu-latest")
            appendLine("    env:")
            appendLine("      CI: \"true\"")
            appendLine("    steps:")
            appendLine("      - uses: actions/checkout@v6")
            appendLine("      - uses: actions/setup-java@v5")
            appendLine("        with:")
            appendLine("          distribution: temurin")
            appendLine("          java-version: $javaVersion")
            if(inputs.cache) appendLine("      - uses: gradle/actions/setup-gradle@v6")
            appendLine("      - run: ./gradlew build -Pmodkit.loader=\${{ matrix.loader }}")

            if(publishJob) {
                appendLine("  publish:")
                appendLine("    if: startsWith(github.ref, 'refs/tags/v')")
                appendLine("    needs: build")
                appendLine("    runs-on: ubuntu-latest")
                appendLine("    steps:")
                appendLine("      - uses: actions/checkout@v6")
                appendLine("      - uses: actions/setup-java@v5")
                appendLine("        with:")
                appendLine("          distribution: temurin")
                appendLine("          java-version: $javaVersion")
                if(inputs.cache) appendLine("      - uses: gradle/actions/setup-gradle@v6")
                appendLine("      - run: ./gradlew modkitPublish")
                appendLine("        env:")
                appendLine("          ${inputs.modrinthSecret}: \${{ secrets.${inputs.modrinthSecret} }}")
                appendLine("          ${inputs.curseforgeSecret}: \${{ secrets.${inputs.curseforgeSecret} }}")
                appendLine("          ${inputs.githubSecret}: \${{ secrets.${inputs.githubSecret} }}")
            }
        }
    }

}
